### ISSUE TITLE
When to release source code and paper?

### ISSUE THREAD

**Issue by Erhushenshou** [windrise/3DGR-CAR#1]
HI, curious to know when the code will be available.

**Comment by windrise** [comment]
Thanks for your interest! Eta for the code and paper is 1 week.

**Comment by Erhushenshou** [comment]
Does this code have details of using 3D Gaussians to reconstruct CBCT /CT from projections?

**Comment by windrise** [comment]
I will show a step-by-step demo. I'm taking time to sort it out.

**Comment by Erhushenshou** [comment]
Would you like to have a connection with me on other platforms such as wechat or qq? I'm seeking some instructions on the code.

**Comment by windrise** [comment]
Of course!
wechat: nifeng_star
