### ISSUE TITLE
Regarding the issue with `input_projs`.

### ISSUE THREAD

**Issue by LZUzgw** [windrise/3DGR-CAR#4]
Thank you for your excellent work! Using your code, I achieved good reconstruction results with 4 projections. However, with only 2 projections, the reconstruction quality seems to decline. After carefully investigating the issue, I found that when the number of projections is set to 2, the `input_projs = ct_projector_train.forward_project(gt_volume)` line produces identical images for both projections in `input_projs`. Could you please advise me on how to address this issue? If you could share your latest updated code, it would be greatly appreciated.

**Comment by windrise** [comment]
In line 34 of the `ct_geometry_projector.py` file, you can modify the projection's "end_angle". 
And, in the `utils` directory, `Compute_intensity.py` and `discretize_grid.cu` provide CUDA implementations for volume rendering. A simple usage example is as follows:

```python
def rendering(pc: GaussianModel, grid):
    # grid: [batchsize, z, x, y, 3]
    # grid_shape = grid.shape
    # expand dimensions for broadcasting
    grid_point = grid.unsqueeze(-2)  # [batchsize, z, x, y, 1, 3]
    z, x, y = grid_point.shape[1:4]
    density_grid = torch.zeros(1, z, x, y, 1, device='cuda', requires_grad=True)
    inv_covariance = pc.get_covariance_inv()
    density_grid = compute_intensity(
        pc.get_xyz.contiguous(),
        grid_point.contiguous(),
        pc.get_density.contiguous(),
        inv_covariance.contiguous(),
        pc.get_scaling.contiguous(),
        density_grid.contiguous(),
    )
    return density_grid
```
